export enum Callback {
  STROKE_WIDTH_CHANGE,
  STROKE_DASH_ARRAY_CHANGE,
  STROKE_COLOR_CHANGE,
  FILL_COLOR_CHANGE,
  FONT_SIZE_CHANGE,
  FONT_COLOR_CHANGE,
  FONT_BACKGROUND_CHANGE,
  STYLE_CHANGE,

  SELECT_TOOl_ON,
  SELECT_TOOl_OFF,
  DRAG_TOOL_ON,
  DRAG_TOOL_OFF,
  HIGHLIGHT_TOOl_ON,
  HIGHLIGHT_TOOl_OFF,
  POINTER_TOOl_ON,
  POINTER_TOOl_OFF,
  EDIT_TOOl_ON,
  EDIT_TOOl_OFF,
  ELLIPSE_TOOL_ON,
  ELLIPSE_TOOL_OFF,
  CIRCLE_TOOL_ON,
  CIRCLE_TOOL_OFF,
  RECTANGLE_TOOL_ON,
  RECTANGLE_TOOL_OFF,
  ISOSCELES_TRIANGLE_TOOL_ON,
  ISOSCELES_TRIANGLE_TOOL_OFF,
  RIGHT_TRIANGLE_TOOL_ON,
  RIGHT_TRIANGLE_TOOL_OFF,
  LINE_TOOL_ON,
  LINE_TOOL_OFF,
  POLYLINE_TOOL_ON,
  POLYLINE_TOOL_OFF,
  POLYGON_TOOL_ON,
  POLYGON_TOOL_OFF,
  FREE_HAND_TOOL_ON,
  FREE_HAND_TOOL_OFF,
  TEXT_TOOL_ON,
  ASSET_EDIT,
  TEXT_TYPING,
  TEXT_TYPING_COMMIT,
  TEXT_TOOL_OFF,
  VIDEO_TOOL_ON,
  VIDEO_TOOL_OFF,
  IMAGE_TOOL_ON,
  IMAGE_TOOL_OFF,
  ASSET_TOOL_ON,
  ASSET_TOOL_OFF,
  GRAPHIC_TOOL_ON,
  GRAPHIC_TOOL_OFF,

  GRID_ON,
  GRID_OFF,
  SNAP_ON,
  SNAP_SIDE_CHANGE,
  SNAP_OFF,
  GROUP,
  UNGROUP,


  POINTER_MOVE,
  POINTER_CHANGE,
  ELEMENT_FOCUSED,
  ELEMENT_BLURRED,
  BLURRED,
  PERFECT_MODE_ON,
  PERFECT_MODE_OFF,


  SELECT_AREA_MOUSE_DOWN,
  SELECT_AREA_MOUSE_MOVE,
  SELECT_AREA_MOUSE_UP,

  HIGHLIGHT_MOUSE_DOWN,
  HIGHLIGHT_MOUSE_MOVE,
  HIGHLIGHT_MOUSE_UP,
  HIGHLIGHTED,

  DRAW_MOUSE_DOWN,
  DRAW_MOUSE_MOVE,
  DRAW_MOUSE_UP,
  STOP_CLICK_DRAWING,
  ELEMENT_CREATED, /* + */

  DRAG_MOUSE_DOWN,
  DRAG_MOUSE_MOVE,
  DRAG_MOUSE_UP,
  NUDGE, /* + */

  NODE_EDIT_MOUSE_DOWN,
  NODE_EDIT_MOUSE_MOVE,
  NODE_EDIT_MOUSE_UP,
  NODE_EDITED, /*  */

  REF_POINT_VIEW_MOUSE_DOWN,
  REF_POINT_VIEW_MOUSE_MOVE,
  REF_POINT_VIEW_MOUSE_UP,
  REF_POINT_CHANGED, /* + */

  RECENTER_REFERENCE_POINT,

  ROTATE_MOUSE_DOWN,
  ROTATE_MOUSE_MOVE,
  ROTATE_MOUSE_UP,
  ELEMENTS_ROTATED, /* + */

  RESIZE_MOUSE_DOWN,
  RESIZE_MOUSE_MOVE,
  RESIZE_MOUSE_UP,
  ELEMENTS_RESIZED, /*  */

  COPY,
  CUT,
  PASTE,
  TO_TOP,
  TO_BOTTOM,
  ELEMENTS_DELETED
}
